// Assembles the standalone Tone.js runtime module the user drops into their
// web game. The emitted source must depend on nothing but `tone` and keep its
// public API stable: startScore, stopScore, setGameMusicState, musicEvent,
// disposeScore (plus the additive read-only getRuntimeInfo).
//
// The emitted source embeds the shared reactive-dynamics decision core from
// ../dynamics.js. Because an emitted .score.js travels alone (it cannot
// import from ./src), the core is spliced into the emitted string as a flat
// script. That flat string is precomputed into ../dynamics.vendored.js
// (generated by dev/scripts/vendor_dynamics.mjs / build.py); this module only
// imports it — it deliberately does NOT read the filesystem here, because
// export runs in the browser. dynamics.js is pure (no Tone/DOM) and only
// imports journeyEnergy from variation.js, which is emitted alongside the
// splice. dev/tests/dynamics-parity.test.js guards that the vendored copy
// never drifts from dynamics.js.
//
// The emitted code itself is split by concern under ./parts/: instrument
// settings + overrides, voice builders, theory (harmony guard), journey
// energy, phrase variation, and the transport/API block a game calls.
import { DYNAMICS_SOURCE } from "../dynamics.vendored.js";
import { SCALES } from "../scales.js";
import { INSTRUMENTS } from "../instruments.js";
import { INSTRUMENT_SETTINGS_SRC } from "./parts/instrument-settings.js";
import { VOICE_BUILDERS_SRC } from "./parts/voice-builders.js";
import { JOURNEY_ENERGY_SRC } from "./parts/journey-energy.js";
import { theorySrc } from "./parts/theory.js";
import { VARIATION_SRC } from "./parts/variation.js";
import { TRANSPORT_API_SRC } from "./parts/transport-api.js";

export function runtimeModule(project) {
  const config = JSON.stringify(project, null, 2);
  const dynamics = DYNAMICS_SOURCE;
  return `import * as Tone from "tone";

export const score = ${config};

const INSTRUMENTS = ${JSON.stringify(INSTRUMENTS)};

${INSTRUMENT_SETTINGS_SRC}

${VOICE_BUILDERS_SRC}

// ---- reactive-dynamics core, spliced from src/music/dynamics.js ----
// __RT_DYN_BEGIN__
${dynamics}
// __RT_DYN_END__

${JOURNEY_ENERGY_SRC}

${theorySrc(JSON.stringify(SCALES))}

${VARIATION_SRC}

${TRANSPORT_API_SRC}
`;
}
