// Builds the standalone Tone.js runtime module the user drops into their web
// game. The emitted source must depend on nothing but `tone` and keep its
// public API stable: startScore, stopScore, setGameMusicState, musicEvent,
// disposeScore.
//
// The source embeds the shared reactive-dynamics decision core from
// ./dynamics.js. Because an emitted .score.js travels alone (it cannot import
// from ./src), the core is spliced into the emitted string as a flat script.
// That flat string is precomputed into ./dynamics.vendored.js (generated by
// dev/scripts/vendor_dynamics.mjs / build.py); this module only imports it —
// it deliberately does NOT read the filesystem here, because export runs in
// the browser. dynamics.js is pure (no Tone/DOM) and only imports journeyEnergy
// from variation.js, which is added to the emitted file just after the splice.
// dev/tests/dynamics-parity.test.js guards that the vendored copy never
// drifts from dynamics.js.
import { DYNAMICS_SOURCE } from "./dynamics.vendored.js";
import { SCALES } from "./scales.js";
import { INSTRUMENTS } from "./instruments.js";

export function runtimeModule(project) {
  const config = JSON.stringify(project, null, 2);
  const dynamics = DYNAMICS_SOURCE;
  return `import * as Tone from "tone";

export const score = ${config};

const INSTRUMENTS = ${JSON.stringify(INSTRUMENTS)};

function instrumentSettings(instrument, role) {
  const preset = INSTRUMENTS[instrument] || INSTRUMENTS["Glass bell"];
  return preset[role];
}

// ---- voice builders (mirror of audio-engine.js) --------------------------
const ROLE_VOLUME = { melody: -9, chords: -16, bass: -11 };
function makePitched(roleKey, cfg) {
  const { voice, pluck, ...options } = cfg;
  if (voice === "pluck") return new Tone.PluckSynth({ ...(pluck || {}), volume: ROLE_VOLUME[roleKey] });
  if (voice === "fm") return new Tone.PolySynth(Tone.FMSynth).set({ ...options, volume: ROLE_VOLUME[roleKey] });
  return new Tone.PolySynth(Tone.Synth).set({ ...options, volume: ROLE_VOLUME[roleKey] });
}
function makeDrums(instrument, reverb, glue) {
  const preset = instrumentSettings(instrument, "percussion");
  const extras = [];
  const kick = new Tone.MembraneSynth({ ...preset.kick, volume: -10 }).toDestination();
  const hatFilter = preset.hatFilter
    ? new Tone.Filter({ type: "highpass", frequency: preset.hatFilter }).connect(reverb)
    : null;
  const hat = new Tone.NoiseSynth({ ...preset.hat, volume: -24 }).connect(hatFilter || reverb);
  if (hatFilter) extras.push(hatFilter);
  let snare = null;
  if (preset.snare) {
    const snareFilter = preset.snareFilter
      ? new Tone.Filter({ type: "bandpass", frequency: preset.snareFilter, Q: 0.8 }).connect(glue)
      : null;
    snare = new Tone.NoiseSynth({ ...preset.snare, volume: -14 }).connect(snareFilter || glue);
    if (snareFilter) extras.push(snareFilter);
    extras.push(snare);
  }
  return { kind: "drums", kick, hat, snare, extras };
}

// ---- reactive-dynamics core, spliced from src/music/dynamics.js ----
// __RT_DYN_BEGIN__
${dynamics}
// __RT_DYN_END__

// supply the one function dynamics.js imports from variation.js
function journeyEnergy(shape, depth, bar, length) {
  const span = Math.max(4, Math.round(length));
  const phase = (((bar % span) + span) % span) / span;
  let raw;
  if (shape === "arc") raw = phase < 0.5 ? phase * 2 : (1 - phase) * 2;
  else if (shape === "tide") raw = 0.5 + 0.5 * Math.sin(phase * Math.PI * 2);
  else return 0.5;
  return 0.5 + (raw - 0.5) * (Math.max(0, Math.min(100, depth)) / 100);
}

const NOTES = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"];
const SCALES = ${JSON.stringify(SCALES)};
function pitchClass(key) {
  return NOTES.indexOf(({ Eb: "D#", Ab: "G#", Bb: "A#" })[key] || key);
}
function note(degree, octave = 4) {
  const scale = SCALES[score.scale];
  const wrapped = ((degree % scale.length) + scale.length) % scale.length;
  const midi = 12 * (octave + 1 + Math.floor(degree / scale.length)) + pitchClass(score.key) + scale[wrapped];
  return NOTES[((midi % 12) + 12) % 12] + (Math.floor(midi / 12) - 1);
}
function chord(degree) {
  return [degree, degree + 2, degree + 4, degree + 6].map((d) => note(d, 3));
}

// ---- deterministic PRNG + long-form drift (mirror of variation.js) ----
const clampDegree = (d) => Math.max(0, Math.min(7, d));
function makeRng(seed) {
  const s = Math.floor(Number(seed));
  if (!Number.isFinite(s) || s <= 0) return Math.random;
  let a = s >>> 0;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
function mutateMotif(rate, steps, rng = Math.random) {
  const out = [...steps];
  const chance = (Math.max(0, Math.min(100, rate)) / 100) * 0.35;
  for (let i = 1; i < out.length - 1; i++) {
    if (rng() >= chance * (out[i] === null ? 0.5 : 1)) continue;
    if (out[i] === null) {
      let before = null;
      for (let j = i - 1; j >= 0; j--) if (out[j] !== null) { before = out[j]; break; }
      let after = null;
      for (let j = i + 1; j < out.length; j++) if (out[j] !== null) { after = out[j]; break; }
      out[i] = clampDegree((before ?? after ?? 0) + (rng() > 0.5 ? 1 : -1));
      continue;
    }
    const roll = rng();
    if (roll < 0.4) {
      out[i] = clampDegree(out[i] + (rng() > 0.5 ? 1 : -1));
    } else if (roll < 0.7) {
      out[i] = null;
    } else {
      const others = [];
      for (let k = 1; k < out.length - 1; k++) if (out[k] !== null && k !== i) others.push(k);
      if (others.length > 0) {
        const swapWith = others[Math.floor(rng() * others.length)];
        out[i] = out[swapWith];
        out[swapWith] = steps[i];
      }
    }
  }
  return out;
}

let context = "explore";
let queuedContext = null;
let victoryQueued = false;
let step = 0;
let loopId = null;
let nodes = null;
let voices = {};
let drumExtras = [];
let perfSteps = {};
let barCount = 0;
const restCounter = {};
const resting = {};
let liveAxes = { intensity: 0.3, tension: 0.25, brightness: 0.7 };
let driftRng = Math.random;

function setup() {
  const master = new Tone.Gain(0.74).toDestination();
  const limiter = new Tone.Limiter(-1).connect(master);
  const glue = new Tone.Compressor({ threshold: -20, ratio: 2.4, attack: 0.01, release: 0.25 }).connect(limiter);
  const reverb = new Tone.Reverb({ decay: 5, wet: score.reverb / 100 }).connect(glue);
  const toneShaper = new Tone.Filter({ type: "lowpass", frequency: 7800 }).connect(glue);
  const motifBus = new Tone.Panner(-0.18).connect(reverb);
  const harmonyBus = new Tone.Panner(0.18).connect(toneShaper);
  nodes = { reverb, glue, limiter, master, toneShaper, motifBus, harmonyBus };
  drumExtras = [];
  voices = {};
  perfSteps = {};
  barCount = 0;
  for (const k of Object.keys(restCounter)) delete restCounter[k];
  for (const k of Object.keys(resting)) delete resting[k];
  for (const layer of score.layers) {
    if (layer.role === "motif") perfSteps[layer.id] = [...layer.steps];
    if (layer.role === "harmony") {
      const synth = makePitched("chords", instrumentSettings(layer.instrument, "harmony")).connect(harmonyBus);
      voices[layer.id] = { kind: "chords", synth };
      nodes[layer.id] = synth;
    } else if (layer.role === "motif") {
      const synth = makePitched("melody", instrumentSettings(layer.instrument, "motif")).connect(motifBus);
      voices[layer.id] = { kind: "melody", synth };
      nodes[layer.id] = synth;
    } else if (layer.role === "bass") {
      const cfg = instrumentSettings(layer.instrument, "bass");
      const synth = cfg.pluck
        ? makePitched("bass", cfg).toDestination()
        : new Tone.MonoSynth({ ...cfg, volume: -11 }).toDestination();
      voices[layer.id] = { kind: "bass", synth };
      nodes[layer.id] = synth;
    } else if (layer.role === "percussion") {
      const drums = makeDrums(layer.instrument, reverb, glue);
      voices[layer.id] = drums;
      nodes[layer.id] = { kick: drums.kick, hat: drums.hat };
      drumExtras.push(...drums.extras);
    }
  }
  const transport = Tone.getTransport();
  transport.bpm.value = score.bpm;
  transport.swing = score.swing / 100 || 0;
  transport.swingSubdivision = "8n";
  loopId = transport.scheduleRepeat((time) => {
    const boundary = step === 0 || step === 8;
    if (boundary && queuedContext) {
      context = queuedContext;
      queuedContext = null;
    }
    if (boundary) {
      liveAxes = easeToward(liveAxes, contextTargets(score, context), 0.5);
      transport.bpm.rampTo(score.bpm + tempoOffset(score, liveAxes), 0.5);
    }
    if (step === 0) {
      barCount += 1;
      const journey = score.journey || { shape: "flat", length: 16, depth: 0 };
      const energy = journeyEnergy(journey.shape, journey.depth, barCount, journey.length);
      for (const layer of score.layers) {
        restCounter[layer.id] = (restCounter[layer.id] || 0) + 1;
        const window = layer.restWindow || 0;
        resting[layer.id] = window > 0 && restCounter[layer.id] % (window + 1) === 0;
        const voice = voices[layer.id];
        if (!voice || layer.muted || resting[layer.id] || !layerActive(layer, liveAxes)) continue;
        const delta = journeyGain(layer, energy);
        if (voice.kind === "drums") {
          voice.kick.volume.rampTo(-10 + delta, 0.8);
          voice.hat.volume.rampTo(-24 + delta, 0.8);
          if (voice.snare) voice.snare.volume.rampTo(-14 + delta, 0.8);
        } else if (voice.synth) {
          const base = voice.kind === "chords" ? -16 : voice.kind === "melody" ? -9 : -11;
          voice.synth.volume.rampTo(Math.max(-40, Math.min(0, base + delta)), 0.8);
        }
      }
    }
    if (boundary) {
      for (const layer of score.layers) {
        if (layer.role === "motif" && !layer.muted && layer.variation > 0) {
          perfSteps[layer.id] = mutateMotif(layer.variation, layer.steps, driftRng);
        }
      }
    }
    const features = {};
    for (const layer of score.layers) features[layer.id] = { steps: perfSteps[layer.id] || layer.steps };
    const restingIds = Object.keys(resting).filter((id) => resting[id]);
    const events = computeStepFrame(score, liveAxes, { features, resting: restingIds }, step, driftRng);
    for (const ev of events) {
      const voice = voices[ev.layerId];
      if (!voice) continue;
      if (ev.kind === "chord") {
        voice.synth.triggerAttackRelease(chord(ev.degree), ev.duration, time + (ev.offset || 0), ev.velocity);
      } else if (ev.kind === "scale") {
        voice.synth.triggerAttackRelease(note(ev.degree, ev.octave), ev.duration, time + (ev.offset || 0), ev.velocity);
      } else if (ev.kind === "kick") {
        voice.kick.triggerAttackRelease(ev.pitch || "D1", ev.duration, time + (ev.offset || 0), ev.velocity);
      } else if (ev.kind === "hat") {
        voice.hat.triggerAttackRelease(ev.duration || "32n", time + (ev.offset || 0), ev.velocity);
      } else if (ev.kind === "snare") {
        const target = voice.snare || voice.hat;
        target.triggerAttackRelease(ev.duration || "16n", time + (ev.offset || 0), ev.velocity);
      }
    }
    if (boundary && victoryQueued) {
      const lead = score.layers.find((layer) => layer.role === "motif" && !layer.muted);
      const synth = lead && voices[lead.id] ? voices[lead.id].synth : null;
      if (synth) [0, 2, 4, 7].forEach((d, i) => synth.triggerAttackRelease(note(d, 5), "16n", time + i * 0.09, 0.65));
      victoryQueued = false;
      context = "explore";
      queuedContext = null;
      liveAxes = { intensity: 0.3, tension: 0.25, brightness: 0.7 };
      transport.bpm.rampTo(score.bpm + tempoOffset(score, liveAxes), 0.5);
    }
    step = (step + 1) % 16;
  }, "8n");
}

export async function startScore() {
  await Tone.start();
  if (!nodes) setup();
  driftRng = makeRng(score.variationSeed || 0);
  Tone.getTransport().start();
}

export function stopScore() {
  Tone.getTransport().stop();
  step = 0;
  driftRng = Math.random;
  barCount = 0;
  liveAxes = { intensity: 0.3, tension: 0.25, brightness: 0.7 };
  for (const k of Object.keys(restCounter)) delete restCounter[k];
  for (const k of Object.keys(resting)) delete resting[k];
  for (const layer of score.layers) {
    if (layer.role === "motif") perfSteps[layer.id] = [...layer.steps];
  }
}

export function setGameMusicState({ threat = 0, inCombat = false } = {}) {
  queuedContext = inCombat || threat > 0.7 ? "combat" : threat > 0.3 ? "unease" : "explore";
}

// After a one-shot event such as "victory" the music resolves back to
// exploration at the next bar boundary.
export function musicEvent(name) {
  if (name === "victory") victoryQueued = true;
}

export function disposeScore() {
  if (loopId !== null) Tone.getTransport().clear(loopId);
  Object.values(nodes || {}).forEach((node) => {
    if (Array.isArray(node)) node.forEach((child) => child.dispose());
    else node.dispose && node.dispose();
  });
  drumExtras.forEach((node) => node.dispose && node.dispose());
  drumExtras = [];
  nodes = null;
  voices = {};
}
`;
}