// Generates src/music/dynamics.vendored.js from the reactive-dynamics core so
// the browser-side runtime-module.js (which cannot read the filesystem) can
// splice the shared decision core into an exported .score.js as a plain
// string.
//
// The source of truth for the core is src/music/dynamics/, a set of
// single-purpose modules re-exported by the src/music/dynamics.js barrel.
// This script concatenates the parts IN THE FIXED ORDER BELOW (the emitted
// script must be self-contained: imports stripped, no cross-file import
// statements), stripping module/export keywords from each so the result is a
// flat script that can be embedded verbatim. The vendored module is
// COMMITTED; rebuild it whenever any part changes (build.py runs this
// automatically).
//
//   node dev/scripts/vendor_dynamics.mjs
//
// The parity test (dev/tests/dynamics-parity.test.js) imports the same
// function here to verify the committed vendored file has not gone stale.
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.dirname(path.dirname(__dirname));

const DYNAMICS_PARTS = [
  "src/music/dynamics/axes.js",
  "src/music/dynamics/humanize.js",
  "src/music/dynamics/gates.js",
  "src/music/dynamics/flourishes.js",
  "src/music/dynamics/sections.js",
  "src/music/dynamics/step-frame.js",
  "src/music/dynamics/arrangement.js",
];

// Strip module/export keywords from a pure dynamics source file so it can run
// as part of a flat script inside an emitted .score.js.
export function stripDynamicsSource(source) {
  return source
    .replace(/^import[^\n]+\n/gm, "")
    .replace(/^export function\s*/gm, "function ")
    .replace(/^export\s*(const|let|var)\s*/gm, "$1 ")
    .replace(/\bexport\s*\{[^}]*\};?\s*/g, "")
    .replace(/^\/\/.*$/gm, "")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

export function dynamicsVendorSource() {
  return DYNAMICS_PARTS.map((rel) => stripDynamicsSource(readFileSync(path.join(ROOT, rel), "utf-8"))).join("\n\n");
}

export function writeVendored() {
  const OUTPUT = path.join(ROOT, "src", "music", "dynamics.vendored.js");
  const stripped = dynamicsVendorSource();
  const contents = `// GENERATED by dev/scripts/vendor_dynamics.mjs — do not edit by hand.
// Rebuild with \`python3 dev/scripts/build.py\` (or node dev/scripts/vendor_dynamics.mjs).
// This is the reactive-dynamics decision core (src/music/dynamics/ parts)
// with module/export keywords stripped, so an emitted .score.js can splice it in.
export const DYNAMICS_SOURCE = ${JSON.stringify(stripped)};
`;
  writeFileSync(OUTPUT, contents);
  return OUTPUT;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const out = writeVendored();
  const stripped = dynamicsVendorSource();
  console.log(`wrote ${path.relative(ROOT, out)} (${stripped.length} chars)`);
}