// Generates src/music/dynamics.vendored.js from src/music/dynamics.js so the
// browser-side runtime-module.js (which cannot read the filesystem) can splice
// the shared decision core into an exported .score.js as a plain string.
//
// The source of truth for the reactive-dynamics core is dynamics.js. This
// script only strips module/export keywords so the result is a flat script
// that can be embedded verbatim. The vendored module is COMMITTED; rebuild it
// whenever dynamics.js changes (build.py runs this automatically).
//
//   node dev/scripts/vendor_dynamics.mjs
//
// The parity test (dev/tests/dynamics-parity.test.js) imports the same
// function here to verify the committed vendored file has not gone stale.
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.dirname(path.dirname(__dirname));
const SRC = path.join(ROOT, "src", "music", "dynamics.js");
const OUTPUT = path.join(ROOT, "src", "music", "dynamics.vendored.js");

// Strip module/export keywords from the pure dynamics source so it can run as
// a flat script inside an emitted .score.js.
export function stripDynamicsSource(source) {
  return source
    .replace(/^import[^\n]+\n/gm, "")
    .replace(/^export function\s*/gm, "function ")
    .replace(/^export\s*(const|let|var)\s*/gm, "$1 ")
    .replace(/\bexport\s*\{[^}]*\};?\s*/g, "")
    .replace(/^\/\/.*$/gm, "")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

export function dynamicsVendorSource() {
  return stripDynamicsSource(readFileSync(SRC, "utf-8"));
}

export function writeVendored() {
  const stripped = dynamicsVendorSource();
  const contents = `// GENERATED by dev/scripts/vendor_dynamics.mjs — do not edit by hand.
// Rebuild with \`python3 dev/scripts/build.py\` (or node dev/scripts/vendor_dynamics.mjs).
// This is the reactive-dynamics decision core (src/music/dynamics.js) with
// module/export keywords stripped, so an emitted .score.js can splice it in.
export const DYNAMICS_SOURCE = ${JSON.stringify(stripped)};
`;
  writeFileSync(OUTPUT, contents);
  return OUTPUT;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const out = writeVendored();
  const stripped = dynamicsVendorSource();
  console.log(`wrote ${path.relative(ROOT, out)} (${stripped.length} chars)`);
}